### ISSUE TITLE
Error building dash

### ISSUE THREAD

**Issue by esb-dev** [WatForm/org.alloytools.alloy#3]
In the build configuration for the dash extension of Alloy is the call of JFlex and Java CUP missing. 

I think one should put the lines

```
-generate: \
    parser/; \
        output=gen/java/; \
        workingdir=gen/java/edu/mit/csail/sdg/parser; \
        generate= \
            "JFlex.Main -d . -nobak ./parser/Alloy.lex; \
             java_cup.Main -dump -parser CompParser -symbols CompSym -compact_red <./parser/Alloy.cup 2>target/report"
```

in file `org.alloytools.alloy.core/bnd.bnd`

Kind regards,
Burkhardt Renz

**Comment by GunnersFiring** [comment]
Thank you for your response. We have been able to resolve the issue.
